### ISSUE TITLE
Wenn zu hässlich mach wieder weg

### ISSUE THREAD

**Issue by ghost** [TheBloodyUnicorns/SMP-Wiki#10]
Ich denke wir wollen die SMP Map schön halten. Sollen wir also wenn jemand was absolut hässliches großes baut was jeder sehen kann, sagen dürfen, dass er es wieder abreißen muss?

**Comment by confusedalex** [comment]
Sehe ich schwierig.
Schönheit ist Geschmack. Außerdem bräuchten wir bestrafungen für nicht einhaltung

**Comment by Rebbit81** [comment]
nö
