### ISSUE TITLE
Vollautomatisierte Farmen verbieten?

### ISSUE THREAD

**Issue by confusedalex** [TheBloodyUnicorns/SMP-Wiki#3]
Wenn ja wie bestrafen und wie herausfinden?

**Comment by Rebbit81** [comment]
ja

**Comment by confusedalex** [comment]
Was ist eine vollautomatisierte Farm?

Sind solche 
![image](https://user-images.githubusercontent.com/29258035/168281042-62c0654c-94bb-4fe0-bc8a-149c61c63238.png)
Farmen auch verboten?

**Comment by Rebbit81** [comment]
die farm ist halbautomatisch weil man die lava aus den dingern rausnehmen muss *micdrop*

**Comment by Rebbit81** [comment]
vollautomatisch heißt, du baust etwas, machst es an und kannst am ende aus einer kiste items rausnehmen

**Comment by confusedalex** [comment]
Damn okay, danke :)
