### ISSUE TITLE
Tod

### ISSUE THREAD

**Issue by Rebbit81** [TheBloodyUnicorns/SMP-Wiki#8]
Downtime: Machen wir eine? Wie lange? *Wie funktioniert das mit dem Jail dann?*
Sollen Items droppen wenn man stirbt? Wenn ja mit Grabstein oder ganz normal?

**Comment by confusedalex** [comment]
Grabstein aus Performancegründe nein
Downtime aus Spielerfahrung nein
Alle Items should get dropped because why not

**Comment by ghost** [comment]
Ich bin schon für eine downtime = fear RP

**Comment by confusedalex** [comment]
> Ich bin schon für eine downtime = fear RP

Wie lange denn? Alles von 5m-24h ist rechtfertigbar

**Comment by ghost** [comment]
20 oder 30 min
