### ISSUE TITLE
Mob Farmen

### ISSUE THREAD

**Issue by confusedalex** [TheBloodyUnicorns/SMP-Wiki#9]
ja/nein?

**Comment by confusedalex** [comment]
@Rebbit81 @81Firefly81 @Chrolblin

**Comment by ghost** [comment]
Ich würde das genauso machen wie bei den Farmen. Automatisch nein, manuell ja.

**Comment by confusedalex** [comment]
Machen wir Beschränkungen wo Mob Farms platziert sein düfen? So ein wierder Tower in der Luft sieht halt auch schon hässlich aus

**Comment by ghost** [comment]
True. Dazu wollte ich auch noch was sagen warte kurz

**Comment by Rebbit81** [comment]
gemacht
